### ISSUE TITLE
Unclear purpose

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/HackMD#1]
The README for this repo should clarify its purpose & intent.

**Comment by ocaisa** [comment]
Hopefully a little clearer now, we can discuss the (potential) merits of this repo next week.

**Comment by ocaisa** [comment]
@tkphd We've got our first set of workshop notes being synched here now so hopefully the use case is clear and we can close this issue?

**Comment by tkphd** [comment]
Yup!
