### ISSUE TITLE
ISO 8601 date stamps

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/HackMD#2]
This repo will be much less confusing if files are named using the [ISO 8601 date format](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates), e.g., `YYYY-MM-DD...`. When files start with the day of the month instead, things get all jumbled.

**Comment by ocaisa** [comment]
You are totally right, I also think we should probably place the workshop notes in a subfolder.

I'll change it after we finish the session tomorrow as I think modifying the name right now will upset HackMD.
